[ejs.landing]
updateAvailableTooltip = "Actualización disponible"
usernamePlaceholder = "Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Ajustes"
serverStatus = "Servidor"
serverStatusPlaceholder = "Cerrado"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esencial"
newsButton = "Noticias"
launchButton = "Jugar"
launchButtonPlaceholder = "&#8226; No Server Selected"
launchDetails = "Por favor, espere.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Cargando.."
newsErrorFailedSpan = "Error al cargar las noticias"
newsErrorRetryButton = "Volver a intentarlo"
newsErrorNoneSpan = "No hay noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Invalid Value"
loginEmailPlaceholder = "EMAIL O USUARIO"
loginPasswordError = "* Obligatorio"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "forgot password?"
loginRememberMeText = "remember me?"
loginButtonText = "LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Need an Account?"
loginPasswordDisclaimer1 = "Your password is sent directly to mojang and never stored."
loginPasswordDisclaimer2 = "{appName} is not affiliated with Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Login Options"
loginWithMicrosoft = "Login with Microsoft"
loginWithMojang = "Login with Mojang"
cancelButton = "Cancel"

[ejs.overlay]
serverSelectHeader = "Available Servers"
serverSelectConfirm = "Select"
serverSelectCancel = "Cancel"
accountSelectHeader = "Select an Account"
accountSelectConfirm = "Select"
accountSelectCancel = "Cancel"

[ejs.settings]
navHeaderText = "Ajustes"
navAccount = "Cuentas"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "About"
navUpdates = "Actualizaciones"
navDone = "Guardar"
tabAccountHeaderText = "Account Settings"
tabAccountHeaderDesc = "Add new accounts or manage existing ones."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Añadir cuenta de Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Añadir cuenta de Mojang"
minecraftTabHeaderText = "Ajustes de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del juego"
launchFullscreenTitle = "Iniciar en pantalla completa."
autoConnectTitle = "Conectarse automáticamente al servidor al iniciarse."
launchDetachedTitle = "Iniciar el proceso de juego separado del lanzador."
launchDetachedDesc = "Si el juego no está desconectado, al cerrar el lanzador también se cerrará el juego."
tabModsHeaderText = "Ajustes de Mods"
tabModsHeaderDesc = "Activar o desactivar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods obligatorios"
optionalMods = "Mods opcionales"
dropinMods = "Drop-in Mods"
addMods = "Añadir mods"
dropinRefreshNote = "(F5 para actualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activa o desactiva los shaders. Ten en cuenta que los shaders sólo funcionarán correctamente en configuraciones potentes. Puedes añadir paquetes personalizados aquí."
selectShaderpack = "Seleccionar Shaderpack"
tabJavaHeaderText = "Configuración de Java"
tabJavaHeaderDesc = "Gestionar la configuración de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "Máxima RAM"
minRAM = "Mínima RAM"
memoryDesc = "La RAM mínima recomendada es de 3 GB. Ajustar los valores mínimo y máximo al mismo valor puede reducir el retraso."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccione el ejecutable Java"
javaExecSelButtonText = "Elegir archivo"
javaExecDesc = "El ejecutable Java se valida antes del lanzamiento del juego."
javaPathDesc = "La ruta debe terminar en <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones adicionales de JVM"
jvmOptsDesc = "Opciones que se proporcionarán a la JVM en tiempo de ejecución. <em>-Xms</em> y <em>-Xmx</em> no debe incluirse."
launcherTabHeaderText = "Ajustes del Launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher."
allowPrereleaseTitle = "Permitir actualizaciones previas."
allowPrereleaseDesc = "Las versiones pre-lanzamientos incluyen nuevas funciones que pueden no haber sido totalmente probadas o integradas.<br>Esto siempre será así si está utilizando una versión pre-lanzamiento."
dataDirectoryTitle = "Directorio de datos"
selectDataDirectory = "Seleccionar directorio de datos"
chooseFolder = "Elegir carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java se almacenarán en el directorio de datos.<br>Las capturas de pantalla y los guardados del mundo se almacenan en la carpeta de instancia para la configuración del servidor correspondiente."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Consulte la información y las notas de la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión estable"
versionText = "Version "
sourceGithub = "Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola DevTools"
releaseNotes = "Notas de la versión"
changelog = "Registro de cambios"
noReleaseNotes = "No hay notas de la versión"
viewReleaseNotes = "Ver las notas de la versión en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del Launcher"
launcherUpdatesHeaderDesc = "Descargue, instale y revise las actualizaciones del launcher."
checkForUpdates = "Buscar actualizaciones"
whatsNew = "Novedades"
updateReleaseNotes = "Actualización de las notas de la versión"

[ejs.waiting]
waitingText = "Esperando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"


[js.discord]
waiting = "Esperando al cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de sesión Microsoft"
microsoftLogoutTitle = "Cierre de sesión Microsoft"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIAR SESIÓN"
success = "ÉXITO"
tryAgain = "Volver a intentarlo"

[js.login.error]
invalidValue = "* Invalid Value"
requiredValue = "* Required"

[js.login.error.unknown]
title = "Unknown Error During Login"
desc = "An unknown error has occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "Please wait.."
failureTitle = "Error During Launch"
failureText = "See console (CTRL + Shift + i) for more details."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "No Account Selected"

[js.landing.selectedServer]
noSelection = "No Server Selected"
loading = "Loading.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "CERRADO"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Checking system info.."
noCompatibleJava = "No Compatible<br>Java Installation Found"
installJavaMessage = "In order to launch Minecraft, you need a 64-bit installation of Java {major}. Would you like us to install a copy?"
installJava = "Install Java"
installJavaManually = "Install Manually"
javaDownloadPrepare = "Preparing Java Download.."
javaDownloadFailureTitle = "Error During Java Download"
javaDownloadFailureText = "See console (CTRL + Shift + i) for more details."
javaRequired = "Java is Required<br>to Launch"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/Adrixgamer78/sclauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "I Understand"
javaRequiredCancel = "Go Back"

[js.landing.downloadJava]
findJdkFailure = "Failed to find OpenJDK distribution."
javaDownloadCorruptedError = "Downloaded JDK has a bad hash, the file may be corrupted."
extractingJava = "Extracting Java"
javaInstalled = "Java Installed!"

[js.landing.dlAsync]
loadingServerInfo = "Loading server information.."
fatalError = "Fatal Error"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "Please wait.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Downloading files.."
errorDuringFileDownloadTitle = "Error During File Download"
preparingToLaunch = "Preparing to launch.."
launchingGame = "Launching game.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/Adrixgamer78/sclauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Done. Enjoy the server!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Checking for News"

[js.landing.discord]
loading = "Cargando juego.."
joining = "Sailing to Westeros!"
joined = "Exploring the Realm!"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft authentication failed. Please try again."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft logout failed. Please try again."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Select Account"
selectedButton = "Selected Account &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Warning<br>This is Your Last Account"
lastAccountWarningMessage = "In order to use the launcher you must be logged into at least one account. You will need to login again after.<br><br>Are you sure you want to log out?"
confirmButton = "I'm Sure"
cancelButton = "Cancel"

[js.settings.authAccountPopulate]
username = "Username"
uuid = "UUID"
selectAccount = "Select Account"
selectedAccount = "Selected Account ✓"
logout = "Log Out"

[js.settings.dropinMods]
removeButton = "Remove"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Main Server"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "Invalid Selection"
requiresJava = "Requires Java {major} x64."
availableOptions = "Available Options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "Nueva versión disponible"
newPreReleaseTitle = "Nueva versión previa disponible"
downloadingButton = "Descargando.."
downloadButton = 'Descarga desde GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cierra el launcher y ejecuta el dmg para actualizar.</span>'
latestVersionTitle = "Está utilizando la última versión"
checkForUpdatesButton = "Buscar actualizaciones"
checkingForUpdatesButton = "Buscando actualizaciones.."

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando actualizaciones..."
installNowButton = "Instalar"
checkForUpdatesButton = "Buscar actualizaciones"
